### ISSUE TITLE
C++: Comments not always highlighted correctly

### ISSUE THREAD

**Issue by Friedrich2** [mate-desktop/pluma#381]
#### Expected behaviour
C++ comments with // should be ended by the next newline character. (Source: [http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4640.pdf](a draft (page 23 / 37 of 1589, section 2.7)) Thus, pluma, should highlight all characters between the character sequence // (outside of strings!) and \n in the same colour.

#### Actual behaviour
pluma does not do this, if the comment contains a ">" sign (I think that it might have been a "<", but only one of the two characters). The coment seems to be ended by this character.

#### Steps to reproduce the behaviour
1. Make a new file "test.cpp" (filename ending is relevant)
2. Open it in pluma.
3. Input "#include<string> // test < test" (without the quotes)

The first "test" word should erroneously have another colour than the second.

#### MATE general version
Unknown. It was the PC of a friend, with at least one ubuntu core update awaiting installation. Since it was not my PC, I am not able to test it for myself. A (rather short) naive testing seemed to show that the problem is independent of the previous #include<...> directive and of other characters in the comment section.

I did not test /* ... */ comments.

I hope that even these tiny pieces of information are sufficient to reproduce this error.

#### Package version
Unknown.

**Comment by sc0w** [comment]
It works fine here in pluma 1.20.2

![2018-11-17_01-26](https://user-images.githubusercontent.com/7734191/48653794-eb690880-ea07-11e8-8de7-f59eb408f0e6.png)

**Comment by Friedrich2** [comment]
Could you please try it with `#include<iostream> // fuers >> und <<` too? (My friend sent me this as mal-functioning. So probably, I mistook > for <.)

Many thanks in advance!

**Comment by lukefromdc** [comment]
I can confirm that the SECOND test example
#include<iostream> // fuers >> und <<
Does in fact terminate the comment prematurely, after the  >> character

**Comment by selectiveduplicate** [comment]
I cant also confirm this. It also happens with gedit though...

**Comment by lukefromdc** [comment]
Not good news, as this means gedit never got a commit to fix this we could backport

**Comment by selectiveduplicate** [comment]
Maybe this has got something to do with gtksourceview that handles the syntax highlighting?

**Comment by lukefromdc** [comment]
That could be and would mean it has to be fixed upstream. I cannot post bug reports against GNOME as have not been able to keep an account there, possibly due to highly modified/locked down browsers and no time to debug their web interface with it.

**Comment by monsta** [comment]
Yes, highlighting is done by GtkSourceView, we can't fix it here.

**Comment by lukefromdc** [comment]
Unfortunately, using GtkSourceView 4 breaks the external-tools plugin, giving these errors:
```

/usr/lib/python2.7/dist-packages/gi/module.py:171: Warning: cannot register existing type 'GtkSourceBuffer'
  g_type = info.get_g_type()
/usr/lib/python2.7/dist-packages/gi/module.py:171: Warning: cannot add private field to invalid (non-instantiatable) type '<invalid>'
  g_type = info.get_g_type()
/usr/lib/python2.7/dist-packages/gi/module.py:171: Warning: g_once_init_leave: assertion 'result != 0' failed
  g_type = info.get_g_type()
/usr/lib/python2.7/dist-packages/gi/module.py:205: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  type_ = g_type.pytype
/usr/lib/python2.7/dist-packages/gi/module.py:219: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  g_type.pytype = wrapper
/usr/lib/python2.7/dist-packages/gi/module.py:219: Warning: g_type_set_qdata: assertion 'node != NULL' failed
  g_type.pytype = wrapper
/usr/lib/x86_64-linux-gnu/pluma/plugins/externaltools/__init__.py:146: Warning: cannot register existing type 'GtkSourceLanguage'
  language = document.get_language()
/usr/lib/x86_64-linux-gnu/pluma/plugins/externaltools/__init__.py:146: Warning: cannot add private field to invalid (non-instantiatable) type '<invalid>'
  language = document.get_language()
/usr/lib/x86_64-linux-gnu/pluma/plugins/externaltools/__init__.py:146: Warning: g_once_init_leave: assertion 'result != 0' failed
  language = document.get_language()
```
So we need some work there before we can switch over to the currently maintained branch of GtkSourceView

**Comment by lukefromdc** [comment]
On still further testing, I found that whatever change had been made to GtkSourceView 4 had been backported to  GtkSourceView3, so this issue is now FIXED at least on Debian Unstable. This is true whether or not GtkSourceView4 is even installed, so I can confirm GNOME devs have fixed the problem. 

@Friedrich2 ? can you retest this and see if you are still having this problem? If not we can close this, if so your distro may not have caught up yet.

**Comment by monsta** [comment]
You need to write something like `#include <iostream>`, as in https://github.com/mate-desktop/pluma/issues/381#issuecomment-439751207... it's not fixed at least in GtkSourceView 3.24.9.
